In [1]:
import requests
import json 
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

from api_keys import g_key 

filepath = "Vertical_Merge.csv"
df = pd.read_csv(filepath)
output_data_file = "Vertical_Merge_LatLng_2020.csv"
df.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2015
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2015
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2015
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2015
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2015

In [2]:
mask = df.Year == 2020
df_2020 = df.loc[mask].reset_index(drop=True)
df_2020.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Finland,1,7.8087,1.063927,0.954330,0.719008,0.949172,0.195445,-0.059482,2020
1,Denmark,2,7.6456,1.077400,0.955991,0.724025,0.951444,0.168489,0.066202,2020
2,Switzerland,3,7.5599,1.097993,0.942847,0.741024,0.921337,0.303728,0.105911,2020
3,Iceland,4,7.5045,1.077256,0.974670,0.730000,0.948892,0.711710,0.246944,2020
4,Norway,5,7.4880,1.108780,0.952487,0.732008,0.955750,0.263218,0.134533,2020

In [5]:
lats = []
lngs = []

#target_url = f'https://maps.googleapis.com/maps/api/geocode/json?address={target_country}&key={g_key}'
for index, row in df_2020.iterrows():
    # get country type from df
    target_country = row['Country']
    
    target_url = f'https://maps.googleapis.com/maps/api/geocode/json?address={target_country}&key={g_key}'
    # assemble url and make API request
    geo_data = requests.get(target_url).json()

    # add keyword to params dict
    lat = geo_data["results"][0]["geometry"]["location"]["lat"]
    lng = geo_data["results"][0]["geometry"]["location"]["lng"]

    lats.append(lat)
    lngs.append(lng)
    
    # extract results
    results = geo_data['results']
    
    time.sleep(1)
    
df_2020["Latitude"]= lats
df_2020["Longitude"] = lngs

In [2]:
df_2020

NameError: name 'df_2020' is not defined

In [7]:
df_2020.to_csv(output_data_file, index=False)