In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
filepath1 = "Clean_2015.csv"
filepath2 = "Clean_2016.csv"
filepath3 = "Clean_2017.csv"
filepath4 = "Clean_2018.csv"
filepath5 = "Clean_2019.csv"
filepath6 = "Clean_2020.csv"

df_2015 = pd.read_csv(filepath1)
df_2015['Year'] = 2015
df_2016 = pd.read_csv(filepath2)
df_2016['Year'] = 2016
df_2017 = pd.read_csv(filepath3)
df_2017['Year'] = 2017
df_2018 = pd.read_csv(filepath4)
df_2018['Year'] = 2018
df_2019 = pd.read_csv(filepath5)
df_2019['Year'] = 2019
df_2020 = pd.read_csv(filepath6)
df_2020['Year'] = 2020

df_2020.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Finland,1,7.8087,10.639267,0.954330,71.900825,0.949172,0.195445,-0.059482,2020
1,Denmark,2,7.6456,10.774001,0.955991,72.402504,0.951444,0.168489,0.066202,2020
2,Switzerland,3,7.5599,10.979933,0.942847,74.102448,0.921337,0.303728,0.105911,2020
3,Iceland,4,7.5045,10.772559,0.974670,73.000000,0.948892,0.711710,0.246944,2020
4,Norway,5,7.4880,11.087804,0.952487,73.200783,0.955750,0.263218,0.134533,2020

In [6]:
datarank = pd.DataFrame(columns = ['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',
                                   'Social Support', 'Health Life Expectancy', 'Freedom','Trust (Government Corruption)',
                                   'Generosity', 'Year'])
n = [df_2015, df_2016, df_2017, df_2018, df_2019, df_2020]
for i in n:
    datarank = datarank.append(i[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',
                                   'Social Support', 'Health Life Expectancy', 'Freedom','Trust (Government Corruption)',
                                   'Generosity', 'Year']], ignore_index = 'True')
datarank

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Switzerland,1,7.5870,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2015
1,Iceland,2,7.5610,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2015
2,Denmark,3,7.5270,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2015
3,Norway,4,7.5220,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2015
4,Canada,5,7.4270,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2015
...,...,...,...,...,...,...,...,...,...,...
930,Central African Republic,149,3.4759,6.625160,0.319460,45.200001,0.640881,0.891807,0.082410,2020
931,Rwanda,150,3.3123,7.600104,0.540835,61.098846,0.900589,0.183541,0.055484,2020
932,Zimbabwe,151,3.2992,7.865712,0.763093,55.617260,0.711458,0.810237,-0.072064,2020
933,South Sudan,152,2.8166,7.425360,0.553707,51.000000,0.451314,0.763417,0.016519,2020
934,Afghanistan,153,2.5669,7.462861,0.470367,52.590000,0.396573,0.933687,-0.096429,2020