In [1]:
# data science imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# linear modelling
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import scipy.stats as sts

In [2]:
filepath1 = "../Resources/Clean_2015.csv"
filepath2 = "../Resources/Clean_2016.csv"
filepath3 = "../Resources/Clean_2017.csv"
filepath4 = "../Resources/Clean_2018.csv"
filepath5 = "../Resources/Clean_2019.csv"
filepath6 = "../Resources/Clean_2020.csv"

df_2015 = pd.read_csv(filepath1)
df_2015['Year'] = 2015
df_2016 = pd.read_csv(filepath2)
df_2016['Year'] = 2016
df_2017 = pd.read_csv(filepath3)
df_2017['Year'] = 2017
df_2018 = pd.read_csv(filepath4)
df_2018['Year'] = 2018
df_2019 = pd.read_csv(filepath5)
df_2019['Year'] = 2019
df_2020 = pd.read_csv(filepath6)
df_2020['Year'] = 2020

df_2016.head()

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2016
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2016
2,Iceland,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2016
3,Norway,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2016
4,Finland,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2016

In [3]:
df_vertical = pd.DataFrame(columns = ['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',
                                   'Social Support', 'Health Life Expectancy', 'Freedom','Trust (Government Corruption)',
                                   'Generosity', 'Year'])
years = [df_2015, df_2016, df_2017, df_2018, df_2019, df_2020]
for year in years:
    df_vertical = df_vertical.append(year[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)',
                                   'Social Support', 'Health Life Expectancy', 'Freedom','Trust (Government Corruption)',
                                   'Generosity', 'Year']], ignore_index = 'True')
df_vertical

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social Support,Health Life Expectancy,Freedom,Trust (Government Corruption),Generosity,Year
0,Switzerland,1,7.5870,1.396510,1.349510,0.941430,0.665570,0.419780,0.296780,2015
1,Iceland,2,7.5610,1.302320,1.402230,0.947840,0.628770,0.141450,0.436300,2015
2,Denmark,3,7.5270,1.325480,1.360580,0.874640,0.649380,0.483570,0.341390,2015
3,Norway,4,7.5220,1.459000,1.330950,0.885210,0.669730,0.365030,0.346990,2015
4,Canada,5,7.4270,1.326290,1.322610,0.905630,0.632970,0.329570,0.458110,2015
...,...,...,...,...,...,...,...,...,...,...
929,Central African Republic,149,3.4759,0.662516,0.319460,0.452000,0.640881,0.891807,0.082410,2020
930,Rwanda,150,3.3123,0.760010,0.540835,0.610988,0.900589,0.183541,0.055484,2020
931,Zimbabwe,151,3.2992,0.786571,0.763093,0.556173,0.711458,0.810237,-0.072064,2020
932,South Sudan,152,2.8166,0.742536,0.553707,0.510000,0.451314,0.763417,0.016519,2020
933,Afghanistan,153,2.5669,0.746286,0.470367,0.525900,0.396573,0.933687,-0.096429,2020

In [4]:
df_vertical.to_csv("../Resources/Vertical_Merge.csv", index=False)